name: Build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
      - '[0-9]+.[0-9]+.[0-9]-rc[0-9]+'
    branches:
      - 'master'
jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sysroot: [riscv64-lp64d-linux-musl]
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: |
          make config sysroot=${{ matrix.sysroot }}
          make ci.env >> $GITHUB_ENV
      - name: cache
        id: portage
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache@v3
        with:
          path: cache/
          key: ${{ runner.os }}.${{ matrix.sysroot }}.${{ env.VERSION }}.${{ github.run_id }}
          fail-on-cache-miss: true
          restore-keys: |
            ${{ runner.os }}.${{ matrix.sysroot }}.${{ env.VERSION }}.${{ github.run_id }}
            ${{ runner.os }}.${{ matrix.sysroot }}.${{ env.VERSION }}.
            ${{ runner.os }}.${{ matrix.sysroot }}.
            ${{ runner.os }}.
      - name: make
        run: |
          make build
        env:
          DOCKER_OPTS: --load --cache-from type=gha --cache-to type=gha,mode=max
      - name: login
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make push
